### ISSUE TITLE
Clarify how to override a color from the color scheme

### ISSUE THREAD

**Issue by dagostinelli** [KevinGoodsell/vim-csexact#14]
Can you clarify how to override colors from the colorscheme?  I ran into it using the situation below.  (I'm also asking for help with my issue -- but I think this is something others probably are running into)

I'm trying to override a color from my colorscheme.  I think csexact is clobbering my changes. It's the color of tabs and spaces.

My vimrc more or less does this:
- `Plugin 'KevinGoodsell/vim-csexact'`
- `set list listchars=tab:>.,trail:.,extends:>,precedes:<`
- `colorscheme cobalt2`
- `highlight SpecialKey ctermfg=8 guifg=gray ctermbg=16`

[The coblat2 colorscheme is from here](https://github.com/herrbischoff/cobalt2.vim/blob/master/colors/cobalt2.vim)

The last line sets the background color to the same as cobalt2 after CS Exact changes it.  I verified which number I should use by issuing `verbose highlight SpecialKey`.  The original color from the cobalt2 colorscheme is 59.  I verified that number [by looking at the code in github.
](https://github.com/herrbischoff/cobalt2.vim/blob/master/colors/cobalt2.vim)

While troubleshooting, I also tried this:
- `CSExactColors`
- `highlight SpecialKey ctermfg=8 guifg=gray ctermbg=59`
- `CSExactColors`

And that just resets it back to the wrong color again.

Can you clarify how to override a color from the colorscheme?

**Comment by KevinGoodsell** [comment]
Hi @dagostinelli, I haven't looked at this plugin much for a while, though I still use it daily. I'm not sure that I include a way to specify overrides, but maybe I can find an explanation for what you are seeing and go from there.

**Comment by KevinGoodsell** [comment]
I think your approach to overriding a colorscheme's colors is flawed, but I can give you an alternative. First, let me explain the issue, which is not specific to CSExact.

My understanding of how Vim uses colorschemes is that the colorscheme can basically be reloaded at any time (OK, probably not *any* time, but just go with it). For example, changing colorschemes with ":colorscheme <newcolors>" obviously loads the new colorscheme. Also, changing certain settings, such as 'background' reloads the colorscheme. It's probably clear that in these cases, your .vimrc will not be re-run, so any override that exists just as a line in your .vimrc will not be applied. So you should treat the colorscheme as something that can be re-applied whenever, and not something that is purely set during startup.

The first and most obvious way to customize a colorscheme would be to edit your local copy of the colorscheme file (making a copy under your user's .vim directory if you were using a system-wide version).

If you prefer not to edit the colorscheme file itself (perhaps so that you can easily update it later without having to track your own changes), here's the approach that I personally use. My .vimrc contains (something similar to) this:

```
augroup Vimrc
    autocmd!
    autocmd ColorScheme * call <SID>TweakColors()
augroup END

function! <SID>TweakColors()
    if get(g:, "colors_name", "") == "cobalt2"
        highlight Comment ctermfg=8 guifg=gray ctermbg=16
    endif
endfunction
```
(Here I switched the group to Comment to make it easier to test.)

I think you could stick the 'highlight' command directly into the autocmd instead of in a function; I do it with a function because I have a few different customizations, not just one. I think you can also leave out the augroup, but I find it's nice to keep autocmds grouped with a name that identifies where they came from (plus I think this helps make .vimrc reloadable by removing all autocmds from the group before defining them).

I think this should work for you, but I'm not entirely sure about the order the autocmds will run in. With my setup TweakColors runs before s:CSExactCheck, but this might depend on how you load CSExact. If the autocmd order is reversed in your setup, I think the terminal colors you provided in your autocmd will be used (not the gui colors). Those colors might not be what you expected, since CSExact redefines the terminal's color palette. I think you can prevent this problem by making sure that your autocmd is defined in your .vimrc before CSExact is loaded. I don't know the "Plugin" command you are using, so I don't know if it loads immediately or just adds the directory to the plugin path to be loaded later. My guess is that this won't be a problem, and it will likely work fine.

**Comment by dagostinelli** [comment]
That worked!  (Actually, the event that worked is VimEnter) I didn't know about autocmd's before now. [I just did a bit of reading](https://learnvimscriptthehardway.stevelosh.com/chapters/12.html). And then I looked at `:h autocmd-events` and discovered `VimEnter`. Thank you!

```
autocmd VimEnter * call TweakColors()
function! TweakColors()
	if get(g:, "colors_name", "") == "cobalt2"
		" color the tabs and spaces grey
		highlight SpecialKey ctermfg=8 guifg=gray ctermbg=16
	endif
endfunction
```

**Comment by KevinGoodsell** [comment]
I would expect using VimEnter to fail in the same ways that using a straight .vimrc command would fail: it only runs once, and doesn't run in all of the other cases where the colorscheme is loaded.
